const Data=
    [
        {
         "id":1,
         "name":"Brijesh",
         "email":"b@gmail.com",
         "age":35,
         "photo":"https://img.freepik.com/free-vector/smiling-young-man-illustration_1308-174669.jpg",
        },
        {
            "id":2,
            "name":"Rajesh",
            "email":"Rajesh@gmail.com",
            "age":25,
            "photo":"https://img.freepik.com/free-vector/smiling-young-man-illustration_1308-173524.jpg",
           },
           {
            "id":3,
            "name":"Vishwa",
            "email":"vishwa@gmail.com",
            "age":24,
            "photo":"https://img.freepik.com/premium-vector/man-avatar-profile-picture-isolated-background-avatar-profile-picture-man_1293239-4866.jpg?semt=ais_hybrid",
           },

           {
            "id":4,
            "name":"Sushil",
            "email":"sushil@gmail.com",
            "age":45,
            "photo":"https://img.freepik.com/premium-vector/man-with-shirt-that-says-he-is-smiling_1187092-34900.jpg?semt=ais_hybrid",
           },
           {
            "id":5,
            "name":"Tej",
            "email":"tej@gmail.com",
            "age":36,
            "photo":"https://images.vexels.com/content/145908/preview/male-avatar-maker-2a7919.png",
           },
    ]
export default Data